//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.otdels = new HashSet<otdel>();
            this.purchases = new HashSet<purchase>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime date_start { get; set; }
        public Nullable<int> id_otdel { get; set; }
        public Nullable<int> id_position { get; set; }
        public Nullable<int> id_specialization { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<otdel> otdels { get; set; }
        public virtual otdel otdel { get; set; }
        public virtual specialization specialization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase> purchases { get; set; }
        public virtual position position { get; set; }
    }
}
